server:
  port: 8090
  servlet:
    context-path: /
spring:
  mvc:
    static-path-pattern: /src/**
  resources:
    static-locations: classpath:/src/
    add-mappings: true
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com 
    port: 587
    protocol: smtp
    username: qppk123@gmail.com
    password: huvozcvaoscprwqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    maria:
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/mercury?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/mercury?useUnicode=yes&characterEncoding=UTF-8
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: root
      password: skrbxo12!@
  jpa:
    hibernate:
      ddl-auto: true
      use-new-id-generator-mappings: false
    properties:
      hibernate:  
        show_sql: false
        format_sql: true
    generate-ddl: true
security:
  oauth2:
    authorization:
      token-key-access: isAuthenticated()
    jwt:
      key-uri: http://localhost:8080/oauth/token_key
#logging:
#  level:
#    root: DEBUG
#    org.springframework.transaction: ERROR