server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://localhost:3306/competition?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: skrbxo12!@
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: true
    properties:
      hibernate:  
        format_sql: true
    generate-ddl: true