server:
  port: 8080
  servlet:
    context-path: /
spring:
    data:
      mariadb:
       jdbc-url: jdbc:mariadb://localhost:3306/competition?characterEncoding=UTF-8
       driver-class-name: org.mariadb.jdbc.Driver
       username: root
       password: skrbxo12!@
      jpa:
       properties:
        hibernate:
         #show_sql: true
         format_sql: true
         temp:
          use_jdbc_metadata_defaults: false
          generate-ddl: true