server:
  port: 8080
  servlet:
    context-path: /
spring:
  h2:
    console:
      enabled: true
      path: /h2console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:\nkt\h2;AUTO_SERVER=TRUE
    username: test
    password: 1234