server:
  port: 8090
  servlet:
    context-path: /
spring:
  mail:
    host: smtp.gmail.com 
    port: 587
    username: qppk123@gmail.com
    password: skrbxo12
    properties:
      mail:
        smtp:
          port: 587
          socketFactory:
            port: 587
          auth: true
          starttls:
            enable: true
  data:
    maria:
      jdbc-url: jdbc:mariadb://localhost:3306/competition?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: skrbxo12!@
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: true
    properties:
      hibernate:  
        format_sql: true
    generate-ddl: true
security:
  oauth2:
    authorization:
      token-key-access: isAuthenticated()
    jwt:
      key-uri: http://localhost:8080/oauth/token_key